// frontend/lib/session.test.ts
import { afterEach, describe, expect, it, vi } from "vitest";

import {
  SESSION_COOKIE,
  checkPassword,
  issueSession,
  rateLimitState,
  readSession,
  recordFailure,
  resetRateLimit,
} from "./session";

// A throwaway secret and the hash of "correct-horse" under it. Generated by
// the same function the app uses, so the test cannot drift from the hashing
// it is meant to describe.
const SECRET = "test-signing-secret";

afterEach(() => {
  vi.unstubAllEnvs();
  vi.useRealTimers();
  resetRateLimit();
});

async function hashOf(password: string): Promise<string> {
  const { hashPassword } = await import("./session");
  return hashPassword(password);
}

describe("checkPassword", () => {
  it("accepts the configured password", async () => {
    vi.stubEnv("ADMIN_PASSWORD_HASH", await hashOf("correct-horse"));

    await expect(checkPassword("correct-horse")).resolves.toBe(true);
  });

  it("rejects a wrong password", async () => {
    vi.stubEnv("ADMIN_PASSWORD_HASH", await hashOf("correct-horse"));

    await expect(checkPassword("battery-staple")).resolves.toBe(false);
  });

  it("refuses everything when no hash is configured", async () => {
    vi.stubEnv("ADMIN_PASSWORD_HASH", "");

    // Fail closed, like the backend's missing-secret rule: an unset variable
    // is a deployment mistake, and "nobody gets in" is the safe reading of it.
    await expect(checkPassword("anything")).resolves.toBe(false);
    await expect(checkPassword("")).resolves.toBe(false);
  });

  it("stores no plaintext — the configured value is a hash", async () => {
    const hash = await hashOf("correct-horse");

    expect(hash).not.toContain("correct-horse");
    expect(hash.length).toBeGreaterThan(32);
  });
});

describe("issueSession / readSession", () => {
  it("round-trips a signed session", async () => {
    vi.stubEnv("SESSION_SECRET", SECRET);

    const token = await issueSession();

    await expect(readSession(token)).resolves.not.toBeNull();
  });

  it("rejects a tampered token", async () => {
    vi.stubEnv("SESSION_SECRET", SECRET);
    const token = await issueSession();

    // Flip the payload but keep the signature: an unsigned cookie would be a
    // login anyone can mint for themselves.
    const [payload, signature] = token.split(".");
    const forged = `${payload}x.${signature}`;

    await expect(readSession(forged)).resolves.toBeNull();
  });

  it("rejects a token signed with a different secret", async () => {
    vi.stubEnv("SESSION_SECRET", SECRET);
    const token = await issueSession();

    vi.stubEnv("SESSION_SECRET", "a-different-secret");

    await expect(readSession(token)).resolves.toBeNull();
  });

  it("rejects an expired session", async () => {
    vi.stubEnv("SESSION_SECRET", SECRET);
    vi.useFakeTimers();
    vi.setSystemTime(new Date("2026-08-29T00:00:00Z"));
    const token = await issueSession();

    // Past the two-hour lifetime the login page advertises.
    vi.setSystemTime(new Date("2026-08-29T03:00:00Z"));

    await expect(readSession(token)).resolves.toBeNull();
  });

  it("accepts a session inside its lifetime", async () => {
    vi.stubEnv("SESSION_SECRET", SECRET);
    vi.useFakeTimers();
    vi.setSystemTime(new Date("2026-08-29T00:00:00Z"));
    const token = await issueSession();

    vi.setSystemTime(new Date("2026-08-29T01:30:00Z"));

    await expect(readSession(token)).resolves.not.toBeNull();
  });

  it("rejects garbage", async () => {
    vi.stubEnv("SESSION_SECRET", SECRET);

    await expect(readSession("")).resolves.toBeNull();
    await expect(readSession("not-a-token")).resolves.toBeNull();
  });

  it("names the cookie once, so nothing has to guess it", () => {
    expect(SESSION_COOKIE).toBe("zj_admin");
  });
});

describe("login rate limiting", () => {
  it("counts down the attempts it will still allow", () => {
    expect(rateLimitState("1.2.3.4").remaining).toBe(5);

    recordFailure("1.2.3.4");

    // The number is returned, not just enforced: a limit the server keeps to
    // itself reads as "my password stopped working" and the user keeps trying
    // until they are locked out.
    expect(rateLimitState("1.2.3.4").remaining).toBe(4);
  });

  it("locks out after the allowance runs out", () => {
    for (let i = 0; i < 5; i++) recordFailure("5.6.7.8");

    const state = rateLimitState("5.6.7.8");
    expect(state.remaining).toBe(0);
    expect(state.lockedUntil).not.toBeNull();
  });

  it("keeps one address's failures away from another", () => {
    recordFailure("1.1.1.1");
    recordFailure("1.1.1.1");

    expect(rateLimitState("2.2.2.2").remaining).toBe(5);
  });

  it("forgets the failures once the window passes", () => {
    vi.useFakeTimers();
    vi.setSystemTime(new Date("2026-08-29T00:00:00Z"));
    for (let i = 0; i < 5; i++) recordFailure("9.9.9.9");
    expect(rateLimitState("9.9.9.9").remaining).toBe(0);

    vi.setSystemTime(new Date("2026-08-29T00:20:00Z"));

    expect(rateLimitState("9.9.9.9").remaining).toBe(5);
  });
});

describe("who the rate limit counts against", () => {
  it("caps what address rotation can buy", () => {
    // The per-address bucket is only as trustworthy as the address, and on a
    // public endpoint the address arrives in a header the caller can write.
    // Rotating it must not hand out fresh allowances forever — past the global
    // ceiling, a brand new address inherits what little is left.
    for (let i = 0; i < 18; i++) recordFailure(`10.0.0.${i}`);

    expect(rateLimitState("10.0.0.99").remaining).toBe(2);
  });

  it("does not punish an unseen address while the pool is healthy", () => {
    // Five failures from elsewhere should not cost a colleague on another
    // connection their own five tries.
    for (let i = 0; i < 5; i++) recordFailure(`10.3.0.${i}`);

    expect(rateLimitState("10.3.0.99").remaining).toBe(5);
  });

  it("locks everyone out once the global allowance is gone", () => {
    for (let i = 0; i < 20; i++) recordFailure(`10.1.0.${i}`);

    const state = rateLimitState("10.1.0.250");
    expect(state.remaining).toBe(0);
    expect(state.lockedUntil).not.toBeNull();
  });

  it("still counts a single address down faster than the global pool", () => {
    recordFailure("10.2.0.1");
    recordFailure("10.2.0.1");

    // Five per address against twenty overall: an ordinary typo hits the
    // address bucket long before it touches the global one.
    expect(rateLimitState("10.2.0.1").remaining).toBe(3);
    expect(rateLimitState("10.2.0.2").remaining).toBe(5);
  });
});
